namespace APC.Kernel;

public enum ApcVariable {
  APC_RABBIT_MQ_HOST,
  APC_RABBIT_MQ_USER,
  APC_RABBIT_MQ_PASS,
    
  APC_REDIS_HOST,
  APC_REDIS_USER,
  APC_REDIS_PASS,
    
  APC_API_HOST,
  APC_API_PORT,
  
  APC_ACM_DIR,
}