global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: minio-job
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: [bp-minio:9000]
  
  - job_name: 'otel'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'bp-telemetry-otel:8889' ]
      - targets: [ 'bp-telemetry-otel:8888' ]

  - job_name: 'tempo'
    static_configs:
      - targets: [ 'bp-telemetry-tempo:3200' ]
