name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [master, development]
    paths-ignore:
      - '**/README.md'
      - '**/*.drawio.svg'
      - 'example/**'
      - 'Compose/**'
  # run it during pull request
  pull_request:

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    strategy:
      matrix: 
        services:
          - name: processor/rancher
            directory: Processor.Rancher

          - name: integration/api
            directory: Integration.API
            
          - name: tracker/scheduler
            directory: Tracker.Scheduler
          
          - name: core/gateway
            directory: Core.Gateway
          
          - name: git-unpack
            directory: Backpack.GitUnpack
          
          - name: processor/container
            directory: Processor.Container

          - name: processor/npm
            directory: Processor.Npm
            
          - name: processor/terraform
            directory: Processor.Terraform
          
          - name: processor/php
            directory: Processor.Php
          
          - name: processor/github-releases
            directory: Processor.Github.Releases

          - name: processor/jetbrains-plugins
            directory: Processor.Jetbrains.Plugins

          - name: processor/jetbrains-ide
            directory: Processor.Jetbrains.IDE
            
          - name: processor/nuget
            directory: Processor.Nuget
            
          - name: processor/maven
            directory: Processor.Maven
            
          - name: processor/pypi
            directory: Processor.Pypi

          - name: processor/helm
            directory: Processor.Helm

          - name: collector/http
            directory: Collector.Http
            
          - name: collector/docker-archive
            directory: Collector.DockerArchive
            
          - name: collector/git
            directory: Collector.Git
            
          - name: collector/wget
            directory: Collector.Wget
            
          - name: collector/router
            directory: Collector.Router
            
          - name: collector/container
            directory: Collector.Container

    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Checkout code
        uses: actions/checkout@v3

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push ${{ matrix.services.name }}
        uses: docker/build-push-action@v6
        with:
          # relative path to the place where source code with Dockerfile is located
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./${{ matrix.services.directory }}/Dockerfile
          # Note: tags has to be all lower-case
          tags: |
            ghcr.io/linus-berg/backpack/${{ matrix.services.name }}:latest
            ghcr.io/linus-berg/backpack/${{ matrix.services.name }}:${{ github.ref_name }}-${{ github.sha }}
          # build on feature branches, push only on main branch
          push: ${{ github.ref_name == 'master' || github.ref_name == 'development' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
   